[package]
name = "rust_29405"
version = "0.1.0"
authors = ["André Puel"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
